node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('dockerbuild') {
     sh 'echo dockerbuild'
   }
   stage('sonarqube tests') {
     sh 'echo sonarqube tests'                            
   }                                     
   stage('docker build/push') {
     sh 'echo sonarqube tests'                                     
   }     
}                                  
                                         
