pipeline {
    agent any
    stages {
        stage('Compile Build Binary') {
            parallel {
                stage('Build X') {
                    steps {
                        sh('echo Build X')
                    }
                }
                stage('Build Y') {
                    steps {
                        sh('echo Build Y')
                    }
                }
            }
        }
    }
}
